# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 27517ebe1bf98c127282fbcf521a29224e1053a0a7e6ac1adfc212174d8e43737c387d618adb205360d3f3c005e9f69592e40f3b5e2c65591e5882bf691b8c4c

test:
  secret_key_base: 7f96854fb26d125a528d9f665c35b8b6db512631e084076ace33ca010688a7fa6800b84680d98e30ec70424bb717500b5a8bc67fd8e6404292f9316fac4754b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
